"""
Count and categorize contributors from processed JSON data.

This script processes the JSON files generated by generate_json.py and extracts
unique contributor names, categorizing them as code contributors (PRs) or
community contributors (issues/discussions).
"""

from dataclasses import dataclass
from typing import Dict, List, Set, Optional
from datetime import datetime

from utils import (
    read_json_file,
    write_sorted_names_to_file,
    ensure_directories_exist,
    parse_datetime,
    extract_author_login,
    GENERATED_JSON_DIR,
    CONTRIBUTOR_NAMES_DIR,
    START_DATE,
    logger,
    DataProcessingError,
)


@dataclass
class ContributorSource:
    """Configuration for a contributor data source."""
    json_file: str
    output_file: str
    apply_date_filter: bool = False
    include_after_filter: bool = True  # True = after date, False = before date


def extract_contributors_from_json(
    json_file: str,
    apply_date_filter: bool = False,
    include_after_filter: bool = True
) -> Set[str]:
    """
    Extract unique contributor logins from a JSON file.

    Args:
        json_file: Path to JSON file containing edges
        apply_date_filter: Whether to apply date filtering
        include_after_filter: If True, include contributions after START_DATE;
                             if False, include contributions before START_DATE

    Returns:
        Set of unique contributor login names

    Raises:
        DataProcessingError: If data extraction fails
    """
    try:
        edges = read_json_file(GENERATED_JSON_DIR / json_file)
        contributors: Set[str] = set()

        logger.info(f"Processing {len(edges)} edges from {json_file}")

        for edge in edges:
            node = edge.get("node", {})

            # Apply date filter if requested
            if apply_date_filter and "createdAt" in node:
                try:
                    created_at = parse_datetime(node["createdAt"])

                    if include_after_filter and created_at < START_DATE:
                        continue
                    if not include_after_filter and created_at >= START_DATE:
                        continue
                except DataProcessingError as e:
                    logger.warning(f"Failed to parse date in {json_file}: {e}")
                    continue

            # Extract author
            author = extract_author_login(node)
            if author:
                contributors.add(author)

            # Extract comment authors
            comments = node.get("comments", {}).get("edges", [])
            for comment_edge in comments:
                comment_node = comment_edge.get("node", {})
                comment_author = extract_author_login(comment_node)
                if comment_author:
                    contributors.add(comment_author)

        logger.info(f"Extracted {len(contributors)} unique contributors from {json_file}")
        return contributors

    except Exception as e:
        raise DataProcessingError(f"Failed to extract contributors from {json_file}: {e}")


def process_contributor_source(source: ContributorSource) -> Set[str]:
    """
    Process a single contributor source and write results to file.

    Args:
        source: Contributor source configuration

    Returns:
        Set of unique contributors

    Raises:
        DataProcessingError: If processing fails
    """
    try:
        contributors = extract_contributors_from_json(
            source.json_file,
            source.apply_date_filter,
            source.include_after_filter
        )

        output_path = CONTRIBUTOR_NAMES_DIR / source.output_file
        write_sorted_names_to_file(contributors, output_path)

        return contributors

    except Exception as e:
        logger.error(f"Failed to process {source.json_file}: {e}")
        raise


def main() -> None:
    """Main execution function."""
    try:
        # Ensure output directories exist
        ensure_directories_exist()

        # Define all contributor sources
        sources = [
            # Autoware main repository
            ContributorSource("autoware_discussions.json", "autoware_discussions.txt"),
            ContributorSource("autoware_issues.json", "autoware_issues.txt"),
            ContributorSource("autoware_prs.json", "autoware_prs.txt",
                            apply_date_filter=True, include_after_filter=True),
            ContributorSource("autoware_prs.json", "autoware_ai_prs.txt",
                            apply_date_filter=True, include_after_filter=False),

            # Autoware universe
            ContributorSource("universe_issues.json", "universe_issues.txt"),
            ContributorSource("universe_prs.json", "universe_prs.txt"),

            # Autoware core
            ContributorSource("autoware_core_issues.json", "autoware_core_issues.txt"),
            ContributorSource("autoware_core_prs.json", "autoware_core_prs.txt"),

            # Autoware msgs
            ContributorSource("autoware_msgs_issues.json", "autoware_msgs_issues.txt"),
            ContributorSource("autoware_msgs_prs.json", "autoware_msgs_prs.txt"),

            # Autoware launch
            ContributorSource("autoware_launch_issues.json", "autoware_launch_issues.txt"),
            ContributorSource("autoware_launch_prs.json", "autoware_launch_prs.txt"),

            # Autoware documentation
            ContributorSource("autoware_documentation_issues.json", "autoware_documentation_issues.txt"),
            ContributorSource("autoware_documentation_prs.json", "autoware_documentation_prs.txt"),

            # Autoware AI repositories
            ContributorSource("autoware_ai_issues.json", "autoware_ai_issues.txt"),
            ContributorSource("autoware_ai_planning_issues.json", "autoware_ai_planning_issues.txt"),
            ContributorSource("autoware_ai_planning_prs.json", "autoware_ai_planning_prs.txt"),
            ContributorSource("autoware_ai_perception_issues.json", "autoware_ai_perception_issues.txt"),
            ContributorSource("autoware_ai_perception_prs.json", "autoware_ai_perception_prs.txt"),
            ContributorSource("autoware_ai_messages_issues.json", "autoware_ai_messages_issues.txt"),
            ContributorSource("autoware_ai_messages_prs.json", "autoware_ai_messages_prs.txt"),
            ContributorSource("autoware_ai_simulation_issues.json", "autoware_ai_simulation_issues.txt"),
            ContributorSource("autoware_ai_simulation_prs.json", "autoware_ai_simulation_prs.txt"),
            ContributorSource("autoware_ai_visualization_issues.json", "autoware_ai_visualization_issues.txt"),
            ContributorSource("autoware_ai_visualization_prs.json", "autoware_ai_visualization_prs.txt"),
            ContributorSource("autoware_ai_drivers_issues.json", "autoware_ai_drivers_issues.txt"),
            ContributorSource("autoware_ai_drivers_prs.json", "autoware_ai_drivers_prs.txt"),
            ContributorSource("autoware_ai_utilities_issues.json", "autoware_ai_utilities_issues.txt"),
            ContributorSource("autoware_ai_utilities_prs.json", "autoware_ai_utilities_prs.txt"),
            ContributorSource("autoware_ai_common_issues.json", "autoware_ai_common_issues.txt"),
            ContributorSource("autoware_ai_common_prs.json", "autoware_ai_common_prs.txt"),
        ]

        # Process each source and collect contributors
        all_contributors: Set[str] = set()
        code_contributors_list: List[Set[str]] = []
        community_contributors_list: List[Set[str]] = []

        for source in sources:
            try:
                contributors = process_contributor_source(source)
                all_contributors.update(contributors)

                # Categorize contributors
                if "_prs.json" in source.json_file:
                    code_contributors_list.append(contributors)
                elif "_discussions.json" in source.json_file or "_issues.json" in source.json_file:
                    community_contributors_list.append(contributors)

            except DataProcessingError as e:
                logger.warning(f"Skipping {source.json_file} due to error: {e}")
                continue

        # Aggregate autoware-specific contributors (non-AI repositories)
        autoware_code_contributors: Set[str] = set()
        autoware_community_contributors: Set[str] = set()

        # Code contributors from main Autoware repos
        for filename in ["autoware_prs.txt", "autoware_core_prs.txt", "universe_prs.txt",
                        "autoware_msgs_prs.txt", "autoware_launch_prs.txt",
                        "autoware_documentation_prs.txt"]:
            try:
                from utils import read_text_file
                contributors = set(read_text_file(CONTRIBUTOR_NAMES_DIR / filename))
                autoware_code_contributors.update(contributors)
            except Exception as e:
                logger.warning(f"Failed to read {filename}: {e}")

        # Community contributors from main Autoware repos
        for filename in ["autoware_discussions.txt", "autoware_issues.txt", "universe_issues.txt",
                        "autoware_msgs_issues.txt", "autoware_launch_issues.txt",
                        "autoware_documentation_issues.txt"]:
            try:
                from utils import read_text_file
                contributors = set(read_text_file(CONTRIBUTOR_NAMES_DIR / filename))
                autoware_community_contributors.update(contributors)
            except Exception as e:
                logger.warning(f"Failed to read {filename}: {e}")

        # Combine for total autoware contributors
        autoware_contributors = autoware_code_contributors | autoware_community_contributors

        # Write aggregated results
        write_sorted_names_to_file(all_contributors, CONTRIBUTOR_NAMES_DIR / "all.txt")
        write_sorted_names_to_file(autoware_code_contributors, CONTRIBUTOR_NAMES_DIR / "autoware_code_contributors.txt")
        write_sorted_names_to_file(autoware_community_contributors, CONTRIBUTOR_NAMES_DIR / "autoware_community_contributors.txt")
        write_sorted_names_to_file(autoware_contributors, CONTRIBUTOR_NAMES_DIR / "autoware_contributors.txt")

        # Log summary
        logger.info(f"Total contributors: {len(all_contributors)}")
        logger.info(f"Autoware code contributors: {len(autoware_code_contributors)}")
        logger.info(f"Autoware community contributors: {len(autoware_community_contributors)}")
        logger.info(f"Total Autoware contributors: {len(autoware_contributors)}")

        logger.info("Successfully completed contributor counting")

    except Exception as e:
        logger.error(f"Fatal error in main execution: {e}")
        raise


if __name__ == "__main__":
    main()
